# Generated by Django 4.0.2 on 2022-03-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_comment_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(help_text='Required and unique', max_length=255, null=True, unique=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='Required and unique', max_length=255, null=True, unique=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, help_text='Not Required', null=True, verbose_name='descritpion'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Not Required', null=True, verbose_name='descritpion'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(help_text='Required', max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(help_text='Required', max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text_en',
            field=models.CharField(help_text='Please add alternative text', max_length=255, null=True, verbose_name='Alternative text'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text_ru',
            field=models.CharField(help_text='Please add alternative text', max_length=255, null=True, verbose_name='Alternative text'),
        ),
        migrations.AddField(
            model_name='productsecification',
            name='name_en',
            field=models.CharField(help_text='Required', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='productsecification',
            name='name_ru',
            field=models.CharField(help_text='Required', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_en',
            field=models.CharField(help_text='Required', max_length=255, null=True, unique=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_ru',
            field=models.CharField(help_text='Required', max_length=255, null=True, unique=True, verbose_name='Product Name'),
        ),
    ]
