# Generated by Django 4.0.2 on 2022-03-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoptions',
            name='delivery_name_en',
            field=models.CharField(help_text='Required', max_length=255, null=True, verbose_name='delivery_name'),
        ),
        migrations.AddField(
            model_name='deliveryoptions',
            name='delivery_name_ru',
            field=models.CharField(help_text='Required', max_length=255, null=True, verbose_name='delivery_name'),
        ),
        migrations.AddField(
            model_name='deliveryoptions',
            name='delivery_timeframe_en',
            field=models.CharField(help_text='Required', max_length=255, null=True, verbose_name='delivery timeframe'),
        ),
        migrations.AddField(
            model_name='deliveryoptions',
            name='delivery_timeframe_ru',
            field=models.CharField(help_text='Required', max_length=255, null=True, verbose_name='delivery timeframe'),
        ),
        migrations.AddField(
            model_name='deliveryoptions',
            name='delivery_window_en',
            field=models.CharField(help_text='Required', max_length=255, null=True, verbose_name='delivery window'),
        ),
        migrations.AddField(
            model_name='deliveryoptions',
            name='delivery_window_ru',
            field=models.CharField(help_text='Required', max_length=255, null=True, verbose_name='delivery window'),
        ),
    ]
